name: Sync latest upstream master into local master

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          git remote add upstream https://github.com/nektos/act.git
          git fetch upstream
          git reset --hard upstream/master
          git push --force origin master
